config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  root "stock_tracker#index"
  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "search_friends", to: 'users#search'
  get 'search_stock', to: 'stocks#search'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through:  :user_stocks

  validates :name, :ticker, presence: true

  def self.iex_new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: "pk_265abf4131ce4b20b209b572159ae167",
      secret_token: Rails.application.credentials.iex_api[:secret_api_key],
      endpoint: 'https://cloud.iexapis.com/v1'
    )

    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.alpha_new_lookup(ticker_symbol)
    require 'alphavantage'
    Alphavantage.configure do |config|
      config.api_key = Rails.application.credentials.alpha_api[:secret_api_key]
    end

    quote = Alphavantage::TimeSeries.new(symbol: ticker_symbol).quote

    if !quote.symbol.nil?
      new(ticker: quote.symbol, name: "undef", last_price: quote.price)
    else
      return nil
    end
  end

  def self.twelve_data_new_lookup(ticker_symbol)
    require 'httparty'
    api_key = Rails.application.credentials.twelve_api[:secret_api_key]
    endpoint = "https://api.twelvedata.com/"

    company_response = HTTParty.get("#{endpoint}stocks?symbol=#{ticker_symbol}&apikey=#{api_key}")
    response = HTTParty.get("#{endpoint}time_series?symbol=#{ticker_symbol}&interval=1min&outputsize=5000&apikey=#{api_key}")

    if response.code == 200
      company_body = JSON.parse(company_response.body)
      company_name = company_body['data'].first['name']
      data = JSON.parse(response.body)
      new(ticker: data['meta']['symbol'], name: company_name, last_price: data['values'].last['close'].to_f.round(2))
    else
      return nil
    end
  rescue => exception
    return nil
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_tracked?(ticker_symbol)
    stocks.where(ticker: ticker_symbol).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_match(param) + last_name_match(param) + email_match(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_match(param)
    matches('first_name', param)
  end

  def self.last_name_match(param)
    matches('last_name', param)
  end

  def self.email_match(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_friend)
    !self.friends.where(id: id_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    current_user.friendships.build(friend_id: params[:friend])
    current_user.save
    if current_user.save
      flash[:notice] = "User followed"
    else
      flash[:alert] = "There was something wrong"
    end
    redirect_to my_friends_path
  end

  def destroy
    current_user.friendships.where(friend_id: params[:id]).first.destroy
    flash[:notice] = "Friend removed"
    redirect_to my_friends_path
  end
end

app/controllers/stock_tracker_controller.rb
class StockTrackerController < ApplicationController
  def index
  end

end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.twelve_data_new_lookup(params[:stock])
      if @stock
        if turbo_frame_request? && turbo_frame_request_id == 'api-res'
          render partial: 'users/result'
        end
      else
        if turbo_frame_request? && turbo_frame_request_id == 'api-res'
          flash.now[:alert] = "#{params[:stock]} is not a valid symbol."
          render partial: 'users/result'
        end
      end
    else
      if turbo_frame_request? && turbo_frame_request_id == 'api-res'
        flash.now[:alert] = "Please enter a symbol to search"
        render partial: 'users/result'
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.twelve_data_new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    UserStock.where(stock: stock, user: current_user.id).first.destroy
    flash[:notice] = "#{stock.ticker} tracking removed"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
    @followed_friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
    if @friends
      if turbo_frame_request? && turbo_frame_request_id == 'f-res'
        render partial: 'users/friend_result'
      end
    else
      if turbo_frame_request? && turbo_frame_request_id == 'f-res'
        flash.now[:alert] = "Couldn't find #{params[:friend]}"
        render partial: 'users/friend_result'
      end
    end
    else
      if turbo_frame_request? && turbo_frame_request_id == 'f-res'
        flash.now[:alert] = "Please enter a friend to search"
        render partial: 'users/friend_result'
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stock_tracker_helper.rb
module StockTrackerHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="col-md-6 col-sm-12 mt-5">
  <div class="card">
    <h5 class="card-header">Following friends</h5>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @followed_friends.each do |friend| %>
            <tr>
              <td><%= friend.full_name %></td>
              <td><%= link_to 'View Profile', user_path(friend),
                              class: 'btn btn-sm btn-success' %>
                <%= button_to "Unfollow", friendship_path(friend),
                                method: :delete,
                                data: { turbo: false },
                                class: 'btn btn-sm btn-warning',
                                form_class: 'd-inline-block'%></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="col-10 mx-auto mt-2 alert alert-<%= message_type == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
    <p class="m-0"><%= message_content %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary px-3 py-2">
  <div class="container-fluid">
    <%= link_to "Stock Tracker", root_path, class: 'navbar-brand' %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'My Portfolio', my_portfolio_path, class: request.path == my_portfolio_path ? 'nav-link active' : 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Friends', my_friends_path, class:  request.path == my_friends_path ? 'nav-link active' : 'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav d-flex">
          <li class="nav-item dropdown">
            <a class="btn btn-secondary dropdown-toggle d-flex gap-1 align-items-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <p class="m-0"><%= fa_icon 'user' %></p>
              <p class="m-0"><%= current_user.full_name %></p>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to user_path(current_user.id), class: 'dropdown-item d-flex align-items-center gap-1' do %>
                  <p class="m-0"><%= fa_icon 'user' %></p>
                  <p class="m-0">My profile</p>
                <% end %></li>
              <li>
                <%= link_to edit_user_registration_path, class: 'dropdown-item d-flex align-items-center gap-1' do %>
                  <p class="m-0"><%= fa_icon 'edit' %> </p>
                  <p class="m-0">Edit account</p>
                <% end %></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><%= button_to "Sign Out", destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
    <div class="row">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/stock_tracker/index.html.erb
<main class="col-md-12 col-lg-12 py-5">
  <div class="row d-flex flex-row align-items-center justify-content-center">
    <div class="col-5">
      <p class="text-muted rt m-0">Welcome to stock tracker</p>
      <h1 class="h1 rt m-0">Track stocks prices and dive into this world</h1>
      <p class="rt m-0">Stock tracker is intelligent portfolio of stocks that help you invest and understand strategies and ideas.</p>
    </div>
    <div class="col-5">
      <%= image_tag 'character-research.svg', class: 'img-fluid rt' %>
    </div>
  </div>
</main>

app/views/stocks/_list.html.erb
<div class="col-12 col-md-12 mb-4 mb-lg-0 col-lg-10 mt-5">
  <div class="card">
    <h5 class="card-header">Following stocks</h5>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                <% if current_user.id == @user.id %>
                  <%= button_to "Remove", user_stock_path(stock), method: :delete, data: { turbo_confirm: "Are you sure?" },
                                class: 'btn btn-sm btn-warning'%>
                <% else %>
                  <% if current_user.can_track_stock?(stock.ticker) %>
                    <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                                  class: 'btn btn-success reload-action', method: :post %>
                  <% else %>
                    <span class="badge text-bg-info">
                      You are already tracking
                      <% unless current_user.under_stock_limit? %>
                        10 stocks
                      <% end %>
                      <% if current_user.stock_tracked?(stock.ticker) %>
                        this stock
                      <% end %>
                    </span>
                  <%  end %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_friend_result.html.erb
<%= turbo_frame_tag "f-res" do %>
  <div class="results-block">
    <%= render 'layouts/flash' %>
  </div>
  <% if @friends %>
    <div class="card card-header results-block">
      <table class="col-md-12">
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><strong>Name: </strong><%= friend.full_name %></td>
              <td><strong>Email: </strong><%= friend.email %></td>
              <td class="d-flex align-items-center gap-2"><strong>Actions: </strong>
                <%= link_to 'View Profile', user_path(friend),
                            class: 'btn btn-sm btn-success',
                            data: {turbo: false} %>
                <% if current_user.not_friends_with?(friend.id) %>
                  <%= button_to 'Follow', friendships_path(friend: friend),
                            class: 'btn btn-sm btn-success d-inline-block', method: :post, form_class: 'd-inline-block',
                            data: {turbo: false} %></td>
                <% else %>
                  <span class="badge text-bg-info">
                    You are friends
                  </span>
                <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/users/_result.html.erb
<%= turbo_frame_tag "api-res" do %>
  <div class="results-block">
    <%= render 'layouts/flash' %>
  </div>
  <% if @stock %>
    <div class="card card-header results-block">
      <strong>Symbol: </strong><%= @stock.ticker %><br>
      <strong>Name: </strong><%= @stock.name %><br>
      <strong>Price: </strong><%= @stock.last_price %><br>
      <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                      class: 'btn btn-success reload-action', method: :post,
                                      data: {turbo_frame: "_top"}%>
      <% else %>
        <span class="badge text-bg-info">
          You are already tracking
          <% unless current_user.under_stock_limit? %>
            10 stocks
          <% end %>
          <% if current_user.stock_tracked?(@stock.ticker) %>
            this stock
          <% end %>
          </span>
      <%  end %>
    </div>
  <% end %>
<% end %>

app/views/users/my_friends.erb
<h1 class="px-3 py-4">My Friends</h1>
<main class="col-md-9 col-lg-12 d-flex flex-column align-items-center">
  <div class="search-area col-8 col-md-6">
    <h3>Search Friends</h3>
    <%= form_tag search_friends_path, data: {turbo_frame: 'f-res'}, remote: true, method: :get do %>
      <div class="form-group row">
        <div class="col-10 p-0">
          <%= text_field_tag :friend, params[:stock], placeholder: "Name...", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-2">
          <%= button_tag type: :submit, class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= turbo_frame_tag 'f-res' do %>
  <% end %>
  <% unless @followed_friends.empty?%>
    <%= render 'friends/list' %>
  <% end %>
</main>

app/views/users/my_portfolio.html.erb
<h1 class="px-3 py-4">My portfolio</h1>
<main class="col-md-9 col-lg-12 d-flex flex-column align-items-center">
  <div class="search-area col-8 col-md-6">
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, data: {turbo_frame: 'api-res'}, remote: true, method: :get do %>
      <div class="form-group row">
        <div class="col-10 p-0">
          <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker...", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-2">
          <%= button_tag type: :submit, class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= turbo_frame_tag "api-res" do %>
  <% end %>
  <% unless @tracked_stocks.empty?%>
    <%= render 'stocks/list' %>
  <% end %>
</main>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<% unless @tracked_stocks.empty? %>
  <%=  render 'stocks/list'  %>
<% else %>
  <p class="lead">This user is not tracking any stocks.</p>
<% end %>